# Generated by Django 4.1 on 2023-10-13 02:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
        migrations.AddField(
            model_name="user",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
    ]
